name = "sub2solange2"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "005d7b3976ab44ad9c756732c30dbf8e" }
]
